#include "Game.h"

Game::Game() {
}

/**
 * @brief Check if the user win the game
 * @param username username
 * @param oppoiteRandomSelectedHeroes auto generated by Hero::oppositeRandomSelectedHeroes()
 * @param selectedHeroes read from GameWindow
 * @param heroSelectd hero selected by user, the key is buttom index
 * @return 1: User win 0: Draw -1: User lose
 */
int Game::hasGame(QString username, QVector<int> oppoiteRandomSelectedHeroes, QVector<int> selectedHeroes,
                   int heroSelectd) {
    // 两个英雄队列的初始化 QVector<Hero::Attributes>

    QVector<int> indices; // Such as [0, 1, 2] means: Hero 0 1 2
    for (int i = 0; i < selectedHeroes.size(); ++i) {
        if (selectedHeroes[i] == 1) {
            indices.append(i);
        }
    }
}

Game::~Game() {
}

void Game::appendDatabase() {
    // TODO
}
