name: Windows

on: [push]

env:
  QT_VERSION: 6.8.0

jobs:
  build:
    name: "Build"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install ninja (linux)
        run: sudo apt install ninja-build
        if: matrix.os == 'ubuntu-latest'
      - name: Install ninja (windows)
        run: choco install ninja
        if: matrix.os == 'windows-latest'

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.1.1
            
        with:
          version: ${{env.QT_VERSION}}

      - name: Call vcvarsall.bat Windows amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build
        run: |
          cmake -S . -B build_dir -G "Ninja Multi-Config"
          cmake --build build_dir --config Release
      - name: Upload Windows Executable
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: build_dir/Release/your_program.exe

      - name: Upload Linux Executable
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: linux-bin
          path: build_dir/your_program
